// SPDX-License-Identifier: AGPL-3.0-only

/** ADO-006: browse and claim the Inbox’s unassigned generated Contracts. */
import { useState } from "react";
import { Link } from "react-router";
import { FormattedMessage, useIntl } from "react-intl";
import type { paths } from "@openlaw/api-client";
import { api } from "../lib/api";
import { Button } from "./ui/button";

export type UnassignedContracts =
  paths["/api/v1/inbox/unassigned-contracts"]["get"]["responses"][200]["content"]["application/json"];
export function UnassignedContractsPanel({
  queue,
  onChange,
}: {
  queue: UnassignedContracts;
  onChange: (queue: UnassignedContracts) => void;
}) {
  const intl = useIntl();
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string>();
  const refused = () =>
    intl.formatMessage({
      id: "inbox.unassignedRefused",
      defaultMessage: "The unassigned Contracts could not be updated. Try again.",
    });
  async function claim(number: number) {
    setBusy(true);
    setError(undefined);
    try {
      const result = await api.POST("/api/v1/inbox/unassigned-contracts/{number}/claim", {
        params: { path: { number } },
        body: {},
      });
      if (result.data)
        onChange({
          ...queue,
          contracts: queue.contracts.filter((row) => row.number !== number),
          total: Math.max(0, queue.total - 1),
        });
      if (result.data || result.response.status === 409 || result.response.status === 404) {
        const refreshed = await api.GET("/api/v1/inbox/unassigned-contracts");
        if (refreshed.data) onChange(refreshed.data);
      }
      if (!result.data) throw new Error(result.error?.detail ?? refused());
    } catch (error) {
      setError(error instanceof Error ? error.message : refused());
    } finally {
      setBusy(false);
    }
  }
  async function more() {
    if (queue.nextCursor === null) return;
    setBusy(true);
    setError(undefined);
    try {
      const { data } = await api.GET("/api/v1/inbox/unassigned-contracts", {
        params: { query: { cursor: queue.nextCursor } },
      });
      if (!data) throw new Error(refused());
      onChange({
        ...data,
        contracts: [
          ...queue.contracts,
          ...data.contracts.filter(
            (row) => !queue.contracts.some((existing) => existing.id === row.id),
          ),
        ],
      });
    } catch (error) {
      setError(error instanceof Error ? error.message : refused());
    } finally {
      setBusy(false);
    }
  }
  return (
    <section
      aria-label={intl.formatMessage({
        id: "inbox.unassignedContracts",
        defaultMessage: "Unassigned contracts",
      })}
      className="space-y-3"
    >
      {error && (
        <p role="alert" className="text-sm text-status-danger-fg">
          {error}
        </p>
      )}
      {!queue.contracts.length ? (
        <div className="rounded-card border border-border-default bg-raised p-12 text-center">
          <h2 className="font-semibold">
            <FormattedMessage
              id="inbox.noUnassigned"
              defaultMessage="No Contracts need a Legal Owner"
            />
          </h2>
          <p className="mt-2 text-sm text-muted">
            <FormattedMessage
              id="inbox.noUnassignedHelp"
              defaultMessage="Generated Contracts without a Legal Owner appear here. Claim one to take responsibility for it."
            />
          </p>
        </div>
      ) : (
        <div className="overflow-x-auto rounded-card border border-border-default bg-raised">
          <table className="w-full text-left text-sm">
            <thead>
              <tr className="border-b border-border-default text-muted">
                <th scope="col" className="px-4 py-3">
                  <FormattedMessage id="inbox.unassignedContract" defaultMessage="Contract" />
                </th>
                <th scope="col" className="px-4 py-3">
                  <FormattedMessage id="inbox.unassignedAutoDoc" defaultMessage="Auto-Doc" />
                </th>
                <th scope="col" className="px-4 py-3">
                  <FormattedMessage id="inbox.unassignedGenerator" defaultMessage="Generated by" />
                </th>
                <th scope="col" className="px-4 py-3">
                  <FormattedMessage id="inbox.column.actions" defaultMessage="Actions" />
                </th>
              </tr>
            </thead>
            <tbody>
              {queue.contracts.map((row) => (
                <tr key={row.id} className="border-b border-border-default last:border-0">
                  <td className="px-4 py-3">
                    <Link
                      className="font-medium text-link hover:underline"
                      to={`/contracts/${row.number}`}
                    >
                      {row.title}
                    </Link>
                    <p className="mt-1 text-xs text-muted">
                      #{row.number} · {intl.formatDate(row.createdAt)}
                    </p>
                  </td>
                  <td className="px-4 py-3">
                    <Link className="text-link hover:underline" to={`/auto-docs/${row.autoDoc.id}`}>
                      {row.autoDoc.name}
                    </Link>
                  </td>
                  <td className="px-4 py-3">{row.generator.displayName}</td>
                  <td className="px-4 py-3">
                    <Button disabled={busy} onClick={() => void claim(row.number)}>
                      <FormattedMessage id="inbox.claim" defaultMessage="Claim" />
                    </Button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
      {queue.nextCursor !== null && (
        <Button variant="secondary" disabled={busy} onClick={() => void more()}>
          <FormattedMessage id="inbox.more" defaultMessage="Show more" />
        </Button>
      )}
    </section>
  );
}
