/* Who Helix Software Group is.
 *
 * One fictional company, described once. Everything the seed writes is
 * drawn from here: people, Entities, Counterparties, Contract titles,
 * Matter titles, Requests. That is what makes the instance read as one
 * business rather than as a list of test rows. Names are invented; the
 * domains are `.example`, which can never resolve.
 */

export const ORG = {
  name: "Helix Software Group",
  domain: "helix.example",
  timezone: "Europe/London",
  locale: "en-US",
};

/** The Administrator the instance is set up with. */
export const ADMIN = {
  email: `blair@${ORG.domain}`,
  displayName: "Blair Wentworth",
  password: "correct-horse-battery",
  title: "General Counsel",
};

/**
 * The legal side of the house. `role` is the DD-013 role; `title` is what
 * the person is called in the business, and only appears in prose.
 */
export const STAFF = [
  {
    email: `daniel.okafor@${ORG.domain}`,
    displayName: "Daniel Okafor",
    role: "administrator",
    title: "Deputy General Counsel",
  },
  {
    email: `nadia.haddad@${ORG.domain}`,
    displayName: "Nadia Haddad",
    role: "legal_team_member",
    title: "Senior Counsel, Commercial",
  },
  {
    email: `priya.raman@${ORG.domain}`,
    displayName: "Priya Raman",
    role: "legal_team_member",
    title: "Counsel, Privacy and Data",
  },
  {
    email: `marcus.oyelaran@${ORG.domain}`,
    displayName: "Marcus Oyelaran",
    role: "legal_team_member",
    title: "Counsel, Employment",
  },
  {
    email: `sofia.lindqvist@${ORG.domain}`,
    displayName: "Sofia Lindqvist",
    role: "legal_team_member",
    title: "Counsel, IP and Product",
  },
  {
    email: `ines.duarte@${ORG.domain}`,
    displayName: "Ines Duarte",
    role: "legal_team_member",
    title: "Legal Operations Manager",
  },
  {
    email: `tom.iwu@${ORG.domain}`,
    displayName: "Tom Iwu",
    role: "legal_team_member",
    title: "Paralegal",
  },
  {
    email: `ravi.menon@${ORG.domain}`,
    displayName: "Ravi Menon",
    role: "contributor",
    title: "Procurement Lead",
  },
  {
    email: `ade.balogun@${ORG.domain}`,
    displayName: "Ade Balogun",
    role: "contributor",
    title: "Sales Operations Manager",
  },
  {
    email: `clara.fontaine@${ORG.domain}`,
    displayName: "Clara Fontaine",
    role: "contributor",
    title: "HR Business Partner",
  },
  {
    email: "hannah.meyer@meyerroth.example",
    displayName: "Hannah Meyer",
    role: "contributor",
    title: "External Counsel, Meyer & Roth",
  },
  {
    email: `gabriel.santos@${ORG.domain}`,
    displayName: "Gabriel Santos",
    role: "legal_team_member",
    title: "Counsel, Corporate (on leave)",
    archived: true,
  },
];

/** The business, who submit Requests through the portal. */
export const BUSINESS_USERS = [
  { email: `jonas.weber@${ORG.domain}`, displayName: "Jonas Weber", title: "Account Executive" },
  { email: `amara.nwosu@${ORG.domain}`, displayName: "Amara Nwosu", title: "Sales Director" },
  {
    email: `felix.brandt@${ORG.domain}`,
    displayName: "Felix Brandt",
    title: "Engineering Manager",
  },
  { email: `mei.tanaka@${ORG.domain}`, displayName: "Mei Tanaka", title: "Marketing Lead" },
  { email: `oliver.grant@${ORG.domain}`, displayName: "Oliver Grant", title: "Finance Analyst" },
  {
    email: `sara.haddadi@${ORG.domain}`,
    displayName: "Sara Haddadi",
    title: "Customer Success Lead",
  },
  { email: `diego.salas@${ORG.domain}`, displayName: "Diego Salas", title: "Partnerships Manager" },
  { email: `lena.vogel@${ORG.domain}`, displayName: "Lena Vogel", title: "People Operations" },
  { email: `karim.aziz@${ORG.domain}`, displayName: "Karim Aziz", title: "IT Manager" },
  {
    email: `rosa.iglesias@${ORG.domain}`,
    displayName: "Rosa Iglesias",
    title: "Procurement Analyst",
  },
];

/**
 * Our own corporate entities (DD-008). `type` names one of the seeded
 * Entity Types; `owner` is the parent in the ownership graph, and the
 * percentage is the Holding the seed records between the two.
 */
export const ENTITIES = [
  {
    legalName: "Helix Software Group, Inc.",
    type: "corporation",
    jurisdiction: "Delaware, United States",
    formedOn: "2012-03-14",
    registrationNumber: "DE-5120884",
    registeredAgent: "Corporate Trust Center",
    registeredAddress: "1209 Orange Street, Wilmington, DE 19801, United States",
    status: "active",
    sharesAuthorized: 100000000,
    sharesIssued: 62400000,
  },
  {
    legalName: "Helix Software Holdings B.V.",
    type: "corporation",
    jurisdiction: "Netherlands",
    formedOn: "2014-06-02",
    registrationNumber: "NL-60338291",
    registeredAgent: "Amstel Corporate Services B.V.",
    registeredAddress: "Gustav Mahlerlaan 10, 1082 PP Amsterdam, Netherlands",
    status: "active",
    owner: { of: "Helix Software Group, Inc.", percent: 100 },
  },
  {
    legalName: "Helix Software Ltd",
    type: "corporation",
    jurisdiction: "England and Wales",
    formedOn: "2014-09-18",
    registrationNumber: "09183774",
    registeredAgent: "Pinnacle Company Secretaries Limited",
    registeredAddress: "70 Wilson Street, London EC2A 2DB, United Kingdom",
    status: "active",
    owner: { of: "Helix Software Holdings B.V.", percent: 100 },
  },
  {
    legalName: "Helix Software GmbH",
    type: "corporation",
    jurisdiction: "Germany",
    formedOn: "2015-02-11",
    registrationNumber: "HRB 178342",
    registeredAgent: "Kanzlei Beckmann Partner mbB",
    registeredAddress: "Maximilianstrasse 35, 80539 Munich, Germany",
    status: "active",
    owner: { of: "Helix Software Holdings B.V.", percent: 100 },
  },
  {
    legalName: "Helix Software SAS",
    type: "corporation",
    jurisdiction: "France",
    formedOn: "2016-04-25",
    registrationNumber: "RCS Paris 820 431 118",
    registeredAgent: "Cabinet Lefevre Associes",
    registeredAddress: "12 rue de la Paix, 75002 Paris, France",
    status: "active",
    owner: { of: "Helix Software Holdings B.V.", percent: 100 },
  },
  {
    legalName: "Helix Software Ireland Limited",
    type: "corporation",
    jurisdiction: "Ireland",
    formedOn: "2016-11-08",
    registrationNumber: "IE-589214",
    registeredAgent: "Liffey Corporate Services Limited",
    registeredAddress: "25 Merrion Square, Dublin 2, D02 XR54, Ireland",
    status: "active",
    owner: { of: "Helix Software Holdings B.V.", percent: 100 },
  },
  {
    legalName: "Helix Software Nordics AB",
    type: "corporation",
    jurisdiction: "Sweden",
    formedOn: "2017-05-19",
    registrationNumber: "559102-4471",
    registeredAgent: "Nordbolag Foretagstjanster AB",
    registeredAddress: "Sveavagen 44, 111 34 Stockholm, Sweden",
    status: "active",
    owner: { of: "Helix Software Holdings B.V.", percent: 100 },
  },
  {
    legalName: "Helix Software Espana, S.L.",
    type: "llc",
    jurisdiction: "Spain",
    formedOn: "2018-01-30",
    registrationNumber: "B-88042199",
    registeredAgent: "Gestoria Ibanez S.L.",
    registeredAddress: "Calle de Serrano 41, 28001 Madrid, Spain",
    status: "active",
    owner: { of: "Helix Software Holdings B.V.", percent: 100 },
  },
  {
    legalName: "Helix Software Italia S.r.l.",
    type: "llc",
    jurisdiction: "Italy",
    formedOn: "2018-07-04",
    registrationNumber: "MI-2104884",
    registeredAgent: "Studio Ferrari e Associati",
    registeredAddress: "Via Monte Napoleone 8, 20121 Milan, Italy",
    status: "active",
    owner: { of: "Helix Software Holdings B.V.", percent: 100 },
  },
  {
    legalName: "Helix Software Poland sp. z o.o.",
    type: "llc",
    jurisdiction: "Poland",
    formedOn: "2019-03-12",
    registrationNumber: "KRS 0000771042",
    registeredAgent: "Kancelaria Nowak i Wspolnicy",
    registeredAddress: "ulica Krolewska 18, 00-103 Warsaw, Poland",
    status: "active",
    owner: { of: "Helix Software Holdings B.V.", percent: 100 },
  },
  {
    legalName: "Helix Software Denmark ApS",
    type: "llc",
    jurisdiction: "Denmark",
    formedOn: "2019-09-27",
    registrationNumber: "CVR 40551928",
    registeredAgent: "Kobenhavn Selskabsservice ApS",
    registeredAddress: "Bredgade 30, 1260 Copenhagen K, Denmark",
    status: "active",
    owner: { of: "Helix Software Holdings B.V.", percent: 100 },
  },
  {
    legalName: "Helix Software Switzerland AG",
    type: "corporation",
    jurisdiction: "Switzerland",
    formedOn: "2020-02-14",
    registrationNumber: "CHE-311.204.887",
    registeredAgent: "Zuger Treuhand AG",
    registeredAddress: "Baarerstrasse 78, 6300 Zug, Switzerland",
    status: "active",
    owner: { of: "Helix Software Holdings B.V.", percent: 100 },
  },
  {
    legalName: "Helix Software Portugal, Unipessoal Lda",
    type: "llc",
    jurisdiction: "Portugal",
    formedOn: "2020-06-08",
    registrationNumber: "PT-515884201",
    registeredAgent: "Atlantico Servicos Societarios Lda",
    registeredAddress: "Avenida da Liberdade 110, 1250-146 Lisbon, Portugal",
    status: "dissolved",
    owner: { of: "Helix Software Holdings B.V.", percent: 100 },
  },
  {
    legalName: "Helix Software Canada ULC",
    type: "corporation",
    jurisdiction: "British Columbia, Canada",
    formedOn: "2017-10-03",
    registrationNumber: "BC1140228",
    registeredAgent: "Pacific Registry Agents Inc.",
    registeredAddress: "666 Burrard Street, Vancouver, BC V6C 2X8, Canada",
    status: "active",
    owner: { of: "Helix Software Group, Inc.", percent: 100 },
  },
  {
    legalName: "Helix Software Mexico, S. de R.L. de C.V.",
    type: "llc",
    jurisdiction: "Mexico",
    formedOn: "2021-01-21",
    registrationNumber: "RFC HSM210121K42",
    registeredAgent: "Corporativo Legal Reforma S.C.",
    registeredAddress: "Paseo de la Reforma 296, 06600 Mexico City, Mexico",
    status: "active",
    owner: { of: "Helix Software Group, Inc.", percent: 100 },
  },
  {
    legalName: "Helix Software do Brasil Ltda",
    type: "llc",
    jurisdiction: "Brazil",
    formedOn: "2021-04-16",
    registrationNumber: "CNPJ 41.228.905/0001-33",
    registeredAgent: "Almeida Servicos Societarios Ltda",
    registeredAddress: "Avenida Paulista 1374, Sao Paulo, SP 01310-100, Brazil",
    status: "active",
    owner: { of: "Helix Software Group, Inc.", percent: 100 },
  },
  {
    legalName: "Helix Software Pty Ltd",
    type: "corporation",
    jurisdiction: "New South Wales, Australia",
    formedOn: "2018-11-22",
    registrationNumber: "ACN 629 402 117",
    registeredAgent: "Harbourside Corporate Pty Ltd",
    registeredAddress: "Level 12, 20 Bond Street, Sydney NSW 2000, Australia",
    status: "active",
    owner: { of: "Helix Software Group, Inc.", percent: 100 },
  },
  {
    legalName: "Helix Software New Zealand Limited",
    type: "corporation",
    jurisdiction: "New Zealand",
    formedOn: "2022-02-09",
    registrationNumber: "NZBN 9429050118842",
    registeredAgent: "Kauri Corporate Services Limited",
    registeredAddress: "88 Shortland Street, Auckland 1010, New Zealand",
    status: "active",
    owner: { of: "Helix Software Pty Ltd", percent: 100 },
  },
  {
    legalName: "Helix Software Singapore Pte. Ltd.",
    type: "corporation",
    jurisdiction: "Singapore",
    formedOn: "2019-06-14",
    registrationNumber: "201921884K",
    registeredAgent: "Raffles Corporate Advisers Pte. Ltd.",
    registeredAddress: "10 Marina Boulevard, Singapore 018983",
    status: "active",
    owner: { of: "Helix Software Group, Inc.", percent: 100 },
  },
  {
    legalName: "Helix Software India Private Limited",
    type: "corporation",
    jurisdiction: "India",
    formedOn: "2019-08-05",
    registrationNumber: "U72900KA2019PTC126441",
    registeredAgent: "Vidhi Corporate Advisors LLP",
    registeredAddress: "Prestige Tower, 100 Feet Road, Bengaluru 560038, India",
    status: "active",
    owner: { of: "Helix Software Singapore Pte. Ltd.", percent: 100 },
  },
  {
    legalName: "Helix Software K.K.",
    type: "corporation",
    jurisdiction: "Japan",
    formedOn: "2020-10-01",
    registrationNumber: "0100-01-224881",
    registeredAgent: "Marunouchi Shoji Jimusho",
    registeredAddress: "2-4-1 Marunouchi, Chiyoda-ku, Tokyo 100-0005, Japan",
    status: "active",
    owner: { of: "Helix Software Singapore Pte. Ltd.", percent: 100 },
  },
  {
    legalName: "Helix Software Korea Yuhan Hoesa",
    type: "llc",
    jurisdiction: "South Korea",
    formedOn: "2022-05-30",
    registrationNumber: "110111-7482201",
    registeredAgent: "Sejong Corporate Services",
    registeredAddress: "521 Teheran-ro, Gangnam-gu, Seoul 06168, South Korea",
    status: "active",
    owner: { of: "Helix Software Singapore Pte. Ltd.", percent: 100 },
  },
  {
    legalName: "Helix Software Israel Ltd",
    type: "corporation",
    jurisdiction: "Israel",
    formedOn: "2021-09-13",
    registrationNumber: "51-604882-7",
    registeredAgent: "Herzliya Corporate Services Ltd",
    registeredAddress: "94 Yigal Alon Street, Tel Aviv 6789155, Israel",
    status: "active",
    owner: { of: "Helix Software Group, Inc.", percent: 100 },
  },
  {
    legalName: "Helix Software FZ-LLC",
    type: "branch",
    jurisdiction: "Dubai, United Arab Emirates",
    formedOn: "2022-11-07",
    registrationNumber: "DSO-FZ-118204",
    registeredAgent: "Dubai Silicon Oasis Authority",
    registeredAddress: "DSO Headquarters Building, Dubai, United Arab Emirates",
    status: "active",
    owner: { of: "Helix Software Group, Inc.", percent: 100 },
  },
  {
    legalName: "Helix Software South Africa (Pty) Ltd",
    type: "corporation",
    jurisdiction: "South Africa",
    formedOn: "2023-03-20",
    registrationNumber: "2023/118402/07",
    registeredAgent: "Sandton Company Secretaries (Pty) Ltd",
    registeredAddress: "135 West Street, Sandton 2196, South Africa",
    status: "dormant",
    owner: { of: "Helix Software Group, Inc.", percent: 100 },
  },
  {
    legalName: "Helix Analytics, Inc.",
    type: "corporation",
    jurisdiction: "Delaware, United States",
    formedOn: "2016-08-30",
    registrationNumber: "DE-6104228",
    registeredAgent: "Corporate Trust Center",
    registeredAddress: "1209 Orange Street, Wilmington, DE 19801, United States",
    status: "active",
    owner: { of: "Helix Software Group, Inc.", percent: 100 },
    note: "Acquired 2021; the analytics product line.",
  },
  {
    legalName: "Helix Data Labs LLC",
    type: "llc",
    jurisdiction: "Delaware, United States",
    formedOn: "2021-07-12",
    registrationNumber: "DE-7204119",
    registeredAgent: "Corporate Trust Center",
    registeredAddress: "1209 Orange Street, Wilmington, DE 19801, United States",
    status: "active",
    owner: { of: "Helix Analytics, Inc.", percent: 100 },
  },
  {
    legalName: "Nimbus Metrics, Inc.",
    type: "corporation",
    jurisdiction: "Delaware, United States",
    formedOn: "2018-05-04",
    registrationNumber: "DE-6884012",
    registeredAgent: "Corporate Trust Center",
    registeredAddress: "1209 Orange Street, Wilmington, DE 19801, United States",
    status: "dormant",
    owner: { of: "Helix Software Group, Inc.", percent: 100 },
    note: "Acquired 2023; being wound down into Helix Analytics.",
  },
  {
    legalName: "Helix Ventures LLC",
    type: "llc",
    jurisdiction: "Delaware, United States",
    formedOn: "2022-01-18",
    registrationNumber: "DE-7412085",
    registeredAgent: "Corporate Trust Center",
    registeredAddress: "1209 Orange Street, Wilmington, DE 19801, United States",
    status: "dormant",
    owner: { of: "Helix Software Group, Inc.", percent: 100 },
  },
  {
    legalName: "Helix Software Foundation",
    type: "other",
    jurisdiction: "Delaware, United States",
    formedOn: "2023-09-05",
    registrationNumber: "DE-7902441",
    registeredAgent: "Corporate Trust Center",
    registeredAddress: "1209 Orange Street, Wilmington, DE 19801, United States",
    status: "active",
    note: "The open-source foundation; no member interest is held.",
  },
];

/** The people recorded against Entities as Officers (ENT-001). */
export const OFFICER_NAMES = [
  "Blair Wentworth",
  "Daniel Okafor",
  "Helena Marsh",
  "Victor Anand",
  "Ingrid Solberg",
  "Peter Nakamura",
  "Rosalind Chen",
  "Etienne Roux",
  "Miriam Adler",
  "Callum Doyle",
  "Yasmin Farouk",
  "Lucas Ferreira",
  "Anneke de Vries",
  "Stefan Kowalski",
  "Naomi Ellis",
  "Arjun Pillai",
];

/** The other side of a Contract or Matter (DD-008). */
export const COUNTERPARTIES = {
  customer: [
    "Northwind Traders Ltd",
    "Contoso Financial Group",
    "Fabrikam Health Systems",
    "Tailspin Logistics BV",
    "Adventure Works Retail",
    "Woodgrove Bank plc",
    "Litware Insurance Company",
    "Proseware Media Group",
    "Lucerne Publishing AG",
    "Wide World Importers",
    "Blue Yonder Airlines",
    "Alpine Ski House GmbH",
    "Humongous Insurance Corp",
    "Consolidated Messenger Inc.",
    "Trey Research Institute",
    "Coho Vineyard Holdings",
    "Fourth Coffee Nordics AB",
    "Graphic Design Institute",
    "Margies Travel Group",
    "Southridge Video Ltd",
    "City Power and Light",
    "Wingtip Toys International",
    "Contoso Pharmaceuticals",
    "Bellows Manufacturing Co.",
  ],
  vendor: [
    "Relecloud Infrastructure Inc.",
    "Datum Hosting Services BV",
    "Cirrus Observability Ltd",
    "VanArsdel Analytics GmbH",
    "Fincastle Payroll Services",
    "Kestrel Facilities Management",
    "Orion Recruitment Partners",
    "Beacon Travel Management",
    "Silverline Security Testing",
    "Quill Translation Services",
    "Harbour Print and Fulfilment",
    "Meridian Benefits Brokers",
    "Copperfield Learning Ltd",
    "Ashgrove Cleaning Services",
  ],
  partner: [
    "Sterling Systems Integrators",
    "Marlow Consulting Group",
    "Ravensbourne Digital Ltd",
    "Kaito Solutions K.K.",
    "Aurora Cloud Partners Pty Ltd",
    "Delta Ridge Advisory LLC",
    "Ostwind Technologie GmbH",
    "Pampas Software SRL",
  ],
  professional: [
    "Meyer and Roth LLP",
    "Ashworth Bell Solicitors",
    "Da Silva e Associados",
    "Kestrel Tax Advisers LLP",
    "Ferrand Avocats AARPI",
    "Whitcombe Employment Law",
  ],
};

/** Every Counterparty name, flat, for the pickers that do not care which kind. */
export const ALL_COUNTERPARTIES = Object.values(COUNTERPARTIES).flat();

export const JURISDICTIONS = [
  "England and Wales",
  "State of Delaware",
  "State of New York",
  "Republic of Ireland",
  "Netherlands",
  "Germany",
  "France",
  "Singapore",
  "New South Wales, Australia",
  "Ontario, Canada",
];

export const CURRENCIES = ["USD", "EUR", "GBP"];
