/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/meta": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Instance metadata */
    get: operations["getMeta"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ProblemInput: {
      /** @default about:blank */
      type: string;
      title: string;
      status: number;
      detail?: string;
      instance?: string;
      errors?: {
        path: string;
        message: string;
      }[];
    };
    MetaInput: {
      /** @constant */
      name: "OpenLaw";
      version: string;
    };
    Problem: {
      /** @default about:blank */
      type: string;
      title: string;
      status: number;
      detail?: string;
      instance?: string;
      errors?: {
        path: string;
        message: string;
      }[];
    };
    Meta: {
      /** @constant */
      name: "OpenLaw";
      version: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getMeta: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Meta"];
        };
      };
      /** @description Problem details (RFC 9457) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
}
