/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/meta": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Instance metadata */
    get: operations["getMeta"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The signed-in user, with their live role and session */
    get: operations["getMe"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/setup": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Whether first-run setup (initial Administrator) is still required */
    get: operations["getSetupStatus"];
    put?: never;
    /** First-run setup: create the initial Administrator */
    post: operations["runSetup"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/invites": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Invite a user (Administrator, Legal Team Member, or Contributor); re-sends the set-password email if they have not activated */
    post: operations["inviteUser"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/magic-link": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Request a portal magic link (DD-010); the response is identical whether or not the address is eligible */
    post: operations["requestMagicLink"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ProblemInput: {
      /** @default about:blank */
      type: string;
      title: string;
      status: number;
      detail?: string;
      instance?: string;
      errors?: {
        path: string;
        message: string;
      }[];
    };
    MetaInput: {
      /** @constant */
      name: "OpenLaw";
      version: string;
    };
    Problem: {
      /** @default about:blank */
      type: string;
      title: string;
      status: number;
      detail?: string;
      instance?: string;
      errors?: {
        path: string;
        message: string;
      }[];
    };
    Meta: {
      /** @constant */
      name: "OpenLaw";
      version: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getMeta: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Meta"];
        };
      };
      /** @description Problem details (RFC 9457) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  getMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            user: {
              id: string;
              email: string;
              displayName: string;
              /** @enum {string} */
              role: "administrator" | "legal_team_member" | "contributor" | "business_user";
            };
            session: {
              id: string;
              /** Format: date-time */
              expiresAt: string;
            };
          };
        };
      };
      /** @description Problem details (RFC 9457) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  getSetupStatus: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            needsSetup: boolean;
          };
        };
      };
      /** @description Problem details (RFC 9457) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  runSetup: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** Format: email */
          email: string;
          displayName: string;
          password: string;
        };
      };
    };
    responses: {
      /** @description Default Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            user: {
              id: string;
              email: string;
              displayName: string;
              /** @enum {string} */
              role: "administrator" | "legal_team_member" | "contributor" | "business_user";
            };
          };
        };
      };
      /** @description Problem details (RFC 9457) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  inviteUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** Format: email */
          email: string;
          displayName: string;
          /** @enum {string} */
          role: "administrator" | "legal_team_member" | "contributor";
        };
      };
    };
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            user: {
              id: string;
              email: string;
              displayName: string;
              /** @enum {string} */
              role: "administrator" | "legal_team_member" | "contributor" | "business_user";
            };
          };
        };
      };
      /** @description Default Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            user: {
              id: string;
              email: string;
              displayName: string;
              /** @enum {string} */
              role: "administrator" | "legal_team_member" | "contributor" | "business_user";
            };
          };
        };
      };
      /** @description Problem details (RFC 9457) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  requestMagicLink: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** Format: email */
          email: string;
        };
      };
    };
    responses: {
      /** @description Default Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            message: string;
          };
        };
      };
      /** @description Problem details (RFC 9457) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
}
