/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/meta": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Instance metadata */
    get: operations["getMeta"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The signed-in user, with their live role and session */
    get: operations["getMe"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/me/preferences": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update the signed-in user's preferences (theme #44, timezone SET-006) */
    patch: operations["updateMyPreferences"];
    trace?: never;
  };
  "/api/v1/auth/setup": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Whether first-run setup (initial Administrator) is still required */
    get: operations["getSetupStatus"];
    put?: never;
    /** First-run setup: create the initial Administrator */
    post: operations["runSetup"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/methods": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** What the login screen may offer (TECH-008): the auth mode, the magic-link toggle, whether outbound email works, and the SSO provider to start, if one is registered */
    get: operations["getAuthMethods"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/invites": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Invite a user (Administrator, Legal Team Member, or Contributor); re-sends the set-password email if they have not activated */
    post: operations["inviteUser"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/invites/{userId}/resend": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Re-send a pending invite's set-password email (SET-005) */
    post: operations["resendInvite"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/invites/{userId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Revoke a pending invite (SET-005): the row is removed and the emailed set-password link stops working */
    delete: operations["revokeInvite"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/sso-providers": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The registered OIDC identity providers (TECH-008), with their client IDs but never their secrets */
    get: operations["listSsoProviders"];
    put?: never;
    /** Register a bring-your-own OIDC identity provider (TECH-008); endpoint discovery runs from the issuer, and the response carries the callback URL to paste into the IdP console */
    post: operations["registerSsoProvider"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/sso-providers/{providerId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update the registered provider (TECH-008): omitted fields keep their stored values, endpoint discovery re-runs from the issuer, and a failed update leaves the provider untouched */
    patch: operations["updateSsoProvider"];
    trace?: never;
  };
  "/api/v1/auth/mode": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The organization's auth mode (TECH-008) */
    get: operations["getAuthMode"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Switch the auth mode (TECH-008): `oidc` closes password sign-in for everyone but Administrators (break-glass); switching never invalidates existing sessions */
    patch: operations["setAuthMode"];
    trace?: never;
  };
  "/api/v1/auth/allowed-domains": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The magic-link domain allowlist (DD-010); empty admits nobody */
    get: operations["getAllowedDomains"];
    /** Replace the magic-link domain allowlist (DD-010); the list is normalised to lower case and enforced on the next request — an empty list closes the portal to everyone */
    put: operations["setAllowedDomains"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/portal": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Open or close magic-link sign-in (DD-010's portal floor); takes effect on the next request, independent of the domain allowlist */
    patch: operations["setMagicLinkEnabled"];
    trace?: never;
  };
  "/api/v1/auth/magic-link": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Request a portal magic link (DD-010); the response is identical whether or not the address is eligible */
    post: operations["requestMagicLink"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/onboarding": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** First-run onboarding state (SET-004), plus whether email is configured */
    get: operations["getOnboardingStatus"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/onboarding/complete": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Mark first-run onboarding finished (SET-004); idempotent, and never reversed — the wizard is first-run only */
    post: operations["completeOnboarding"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/org/general": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The organization's identity (SET-001 General pane) */
    get: operations["getOrgGeneral"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update the organization's identity; applies immediately (SET-003) and appends one audit entry per changed field */
    patch: operations["updateOrgGeneral"];
    trace?: never;
  };
  "/api/v1/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Every user with role, status, and last-active (SET-005); pending invites appear as rows with status `invited` */
    get: operations["listUsers"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/{userId}/role": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Change a user's role in place (SET-005); effective on the target's next request — the guard chain reads the role live */
    patch: operations["updateUserRole"];
    trace?: never;
  };
  "/api/v1/users/{userId}/archive": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Archive a user (SET-005): sign-in is blocked and every live session is revoked in the same operation */
    post: operations["archiveUser"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/{userId}/unarchive": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Restore an archived user (SET-003's recovery story): sign-in works again; the sessions archive revoked stay revoked */
    post: operations["unarchiveUser"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/{userId}/revoke-sessions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Revoke every live session of a user (SET-005's lost-laptop case); the account itself is untouched */
    post: operations["revokeUserSessions"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/email-settings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Where outbound email is configured (#37): environment, app, or not at all — and the effective from-address. Never the relay URL */
    get: operations["getEmailSettings"];
    /** Save the app SMTP relay (#37): smtp:// or smtps:// URL with credentials inline, plus a from-address; both null clears. Takes effect on the next send. Refused while the environment pins SMTP — env always wins over app configuration */
    put: operations["saveEmailSettings"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/email-settings/test": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Send a test email through the currently resolved mailer to the signed-in Administrator's own address (#37); fails loudly with a plain-language reason */
    post: operations["sendTestEmail"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/contract-types": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The contract-type taxonomy in display order (CTR-002); archived rows only with includeArchived=true */
    get: operations["listContractTypes"];
    put?: never;
    /** Add a contract type: the slug is derived here, once, and is immutable after creation; the row appends to the display order */
    post: operations["createContractType"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/contract-types/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Hard-delete a contract type; `other` refuses (CTR-002), and once contracts exist (M8) an in-use type will refuse too */
    delete: operations["deleteContractType"];
    options?: never;
    head?: never;
    /** Rename a contract type's display name (DES-017 in-place rename); the slug never changes, and even `other` may rename */
    patch: operations["renameContractType"];
    trace?: never;
  };
  "/api/v1/contract-types/order": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Apply a full permutation of the live rows (SET-003 immediate apply); display orders renumber from 1, archived rows keep theirs */
    put: operations["reorderContractTypes"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/contract-types/{id}/archive": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Archive a contract type (SET-003 guarded): it leaves pickers and the default list; nothing is deleted; `other` refuses */
    post: operations["archiveContractType"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/contract-types/{id}/restore": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Restore an archived contract type (SET-003's recovery story) to the end of the display order */
    post: operations["restoreContractType"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ProblemInput: {
      /** @default about:blank */
      type: string;
      title: string;
      status: number;
      detail?: string;
      instance?: string;
      errors?: {
        path: string;
        message: string;
      }[];
    };
    MetaInput: {
      /** @constant */
      name: "OpenLaw";
      version: string;
    };
    Problem: {
      /** @default about:blank */
      type: string;
      title: string;
      status: number;
      detail?: string;
      instance?: string;
      errors?: {
        path: string;
        message: string;
      }[];
    };
    Meta: {
      /** @constant */
      name: "OpenLaw";
      version: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getMeta: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Meta"];
        };
      };
      /** @description Problem details (RFC 9457) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  getMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            user: {
              id: string;
              email: string;
              displayName: string;
              /** @enum {string} */
              role: "administrator" | "legal_team_member" | "contributor" | "business_user";
              /** @enum {string} */
              theme: "light" | "warm" | "dark";
              image: string | null;
              timezone: string | null;
            };
            session: {
              id: string;
              /** Format: date-time */
              expiresAt: string;
            };
          };
        };
      };
      /** @description Problem details (RFC 9457) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  updateMyPreferences: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** @enum {string} */
          theme?: "light" | "warm" | "dark";
          timezone?: string | null;
        };
      };
    };
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            user: {
              id: string;
              email: string;
              displayName: string;
              /** @enum {string} */
              role: "administrator" | "legal_team_member" | "contributor" | "business_user";
              /** @enum {string} */
              theme: "light" | "warm" | "dark";
              image: string | null;
              timezone: string | null;
            };
          };
        };
      };
      /** @description Problem details (RFC 9457) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  getSetupStatus: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            needsSetup: boolean;
          };
        };
      };
      /** @description Problem details (RFC 9457) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  runSetup: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** Format: email */
          email: string;
          displayName: string;
          password: string;
        };
      };
    };
    responses: {
      /** @description Default Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            user: {
              id: string;
              email: string;
              displayName: string;
              /** @enum {string} */
              role: "administrator" | "legal_team_member" | "contributor" | "business_user";
              /** @enum {string} */
              theme: "light" | "warm" | "dark";
              image: string | null;
              timezone: string | null;
            };
          };
        };
      };
      /** @description Problem details (RFC 9457) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  getAuthMethods: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {string} */
            mode: "built_in" | "oidc";
            magicLinkEnabled: boolean;
            emailConfigured: boolean;
            ssoProviderId: string | null;
          };
        };
      };
      /** @description Problem details (RFC 9457) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  inviteUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** Format: email */
          email: string;
          displayName: string;
          /** @enum {string} */
          role: "administrator" | "legal_team_member" | "contributor";
        };
      };
    };
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            user: {
              id: string;
              email: string;
              displayName: string;
              /** @enum {string} */
              role: "administrator" | "legal_team_member" | "contributor" | "business_user";
              /** @enum {string} */
              theme: "light" | "warm" | "dark";
              image: string | null;
              timezone: string | null;
            };
          };
        };
      };
      /** @description Default Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            user: {
              id: string;
              email: string;
              displayName: string;
              /** @enum {string} */
              role: "administrator" | "legal_team_member" | "contributor" | "business_user";
              /** @enum {string} */
              theme: "light" | "warm" | "dark";
              image: string | null;
              timezone: string | null;
            };
          };
        };
      };
      /** @description Problem details (RFC 9457) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  resendInvite: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            user: {
              id: string;
              email: string;
              displayName: string;
              /** @enum {string} */
              role: "administrator" | "legal_team_member" | "contributor" | "business_user";
              /** @enum {string} */
              theme: "light" | "warm" | "dark";
              image: string | null;
              timezone: string | null;
            };
          };
        };
      };
      /** @description Problem details (RFC 9457) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  revokeInvite: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Default Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Problem details (RFC 9457) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  listSsoProviders: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            providers: {
              id: string;
              providerId: string;
              issuer: string;
              domain: string;
              clientId: string | null;
            }[];
          };
        };
      };
      /** @description Problem details (RFC 9457) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  registerSsoProvider: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          providerId: string;
          /** Format: uri */
          issuer: string;
          domain: string;
          clientId: string;
          clientSecret: string;
        };
      };
    };
    responses: {
      /** @description Default Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            provider: {
              id: string;
              providerId: string;
              issuer: string;
              domain: string;
            };
            callbackUrl: string;
          };
        };
      };
      /** @description Problem details (RFC 9457) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  updateSsoProvider: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        providerId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** Format: uri */
          issuer?: string;
          domain?: string;
          clientId?: string;
          clientSecret?: string;
        };
      };
    };
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            provider: {
              id: string;
              providerId: string;
              issuer: string;
              domain: string;
            };
            callbackUrl: string;
          };
        };
      };
      /** @description Problem details (RFC 9457) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  getAuthMode: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {string} */
            mode: "built_in" | "oidc";
          };
        };
      };
      /** @description Problem details (RFC 9457) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  setAuthMode: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** @enum {string} */
          mode: "built_in" | "oidc";
        };
      };
    };
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {string} */
            mode: "built_in" | "oidc";
          };
        };
      };
      /** @description Problem details (RFC 9457) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  getAllowedDomains: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            domains: string[];
          };
        };
      };
      /** @description Problem details (RFC 9457) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  setAllowedDomains: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          domains: string[];
        };
      };
    };
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            domains: string[];
          };
        };
      };
      /** @description Problem details (RFC 9457) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  setMagicLinkEnabled: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          magicLinkEnabled: boolean;
        };
      };
    };
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            magicLinkEnabled: boolean;
          };
        };
      };
      /** @description Problem details (RFC 9457) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  requestMagicLink: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** Format: email */
          email: string;
        };
      };
    };
    responses: {
      /** @description Default Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            message: string;
          };
        };
      };
      /** @description Problem details (RFC 9457) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  getOnboardingStatus: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            completed: boolean;
            emailConfigured: boolean;
          };
        };
      };
      /** @description Problem details (RFC 9457) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  completeOnboarding: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            completed: boolean;
            emailConfigured: boolean;
          };
        };
      };
      /** @description Problem details (RFC 9457) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  getOrgGeneral: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            general: {
              name: string;
              logo: string | null;
              /** @enum {string} */
              defaultLocale: "en-US";
              defaultTimezone: string;
            };
          };
        };
      };
      /** @description Problem details (RFC 9457) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  updateOrgGeneral: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          name?: string;
          logo?: string | null;
          /** @enum {string} */
          defaultLocale?: "en-US";
          defaultTimezone?: string;
        };
      };
    };
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            general: {
              name: string;
              logo: string | null;
              /** @enum {string} */
              defaultLocale: "en-US";
              defaultTimezone: string;
            };
          };
        };
      };
      /** @description Problem details (RFC 9457) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  listUsers: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            users: {
              id: string;
              email: string;
              displayName: string;
              /** @enum {string} */
              role: "administrator" | "legal_team_member" | "contributor" | "business_user";
              /** @enum {string} */
              status: "active" | "invited" | "archived";
              lastActiveAt: string | null;
            }[];
          };
        };
      };
      /** @description Problem details (RFC 9457) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  updateUserRole: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** @enum {string} */
          role: "administrator" | "legal_team_member" | "contributor" | "business_user";
        };
      };
    };
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            user: {
              id: string;
              email: string;
              displayName: string;
              /** @enum {string} */
              role: "administrator" | "legal_team_member" | "contributor" | "business_user";
              /** @enum {string} */
              status: "active" | "invited" | "archived";
              lastActiveAt: string | null;
            };
          };
        };
      };
      /** @description Problem details (RFC 9457) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  archiveUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            user: {
              id: string;
              email: string;
              displayName: string;
              /** @enum {string} */
              role: "administrator" | "legal_team_member" | "contributor" | "business_user";
              /** @enum {string} */
              status: "active" | "invited" | "archived";
              lastActiveAt: string | null;
            };
          };
        };
      };
      /** @description Problem details (RFC 9457) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  unarchiveUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            user: {
              id: string;
              email: string;
              displayName: string;
              /** @enum {string} */
              role: "administrator" | "legal_team_member" | "contributor" | "business_user";
              /** @enum {string} */
              status: "active" | "invited" | "archived";
              lastActiveAt: string | null;
            };
          };
        };
      };
      /** @description Problem details (RFC 9457) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  revokeUserSessions: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Default Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Problem details (RFC 9457) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  getEmailSettings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {string} */
            source: "env" | "app" | "unset";
            fromAddress: string | null;
          };
        };
      };
      /** @description Problem details (RFC 9457) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  saveEmailSettings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          smtpUrl: string | null;
          smtpFrom: string | null;
        };
      };
    };
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {string} */
            source: "env" | "app" | "unset";
            fromAddress: string | null;
          };
        };
      };
      /** @description Problem details (RFC 9457) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  sendTestEmail: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {boolean} */
            delivered: true;
            to: string;
          };
        };
      };
      /** @description Problem details (RFC 9457) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  listContractTypes: {
    parameters: {
      query?: {
        includeArchived?: "true" | "false";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            contractTypes: {
              id: string;
              slug: string;
              displayName: string;
              displayOrder: number;
              isSystemDefault: boolean;
              archivedAt: string | null;
              inUseCount: number;
            }[];
          };
        };
      };
      /** @description Problem details (RFC 9457) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  createContractType: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          displayName: string;
        };
      };
    };
    responses: {
      /** @description Default Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            contractType: {
              id: string;
              slug: string;
              displayName: string;
              displayOrder: number;
              isSystemDefault: boolean;
              archivedAt: string | null;
              inUseCount: number;
            };
          };
        };
      };
      /** @description Problem details (RFC 9457) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  deleteContractType: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Default Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Problem details (RFC 9457) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  renameContractType: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          displayName: string;
        };
      };
    };
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            contractType: {
              id: string;
              slug: string;
              displayName: string;
              displayOrder: number;
              isSystemDefault: boolean;
              archivedAt: string | null;
              inUseCount: number;
            };
          };
        };
      };
      /** @description Problem details (RFC 9457) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  reorderContractTypes: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          ids: string[];
        };
      };
    };
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            contractTypes: {
              id: string;
              slug: string;
              displayName: string;
              displayOrder: number;
              isSystemDefault: boolean;
              archivedAt: string | null;
              inUseCount: number;
            }[];
          };
        };
      };
      /** @description Problem details (RFC 9457) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  archiveContractType: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          reassignToId?: string;
        };
      };
    };
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            contractType: {
              id: string;
              slug: string;
              displayName: string;
              displayOrder: number;
              isSystemDefault: boolean;
              archivedAt: string | null;
              inUseCount: number;
            };
          };
        };
      };
      /** @description Problem details (RFC 9457) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  restoreContractType: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            contractType: {
              id: string;
              slug: string;
              displayName: string;
              displayOrder: number;
              isSystemDefault: boolean;
              archivedAt: string | null;
              inUseCount: number;
            };
          };
        };
      };
      /** @description Problem details (RFC 9457) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
}
