// SPDX-License-Identifier: AGPL-3.0-only

import { FormattedMessage } from "react-intl";
import { Link } from "react-router";
import type { TableCatalogue } from "../../lib/list-views";
import { contractReference } from "../../lib/contracts";
import { formatRelativeOrShort } from "../../lib/format";
import type { UnassignedContracts } from "../unassigned-contracts";

export type UnassignedContract = UnassignedContracts["contracts"][number];
const linkClass =
  "truncate rounded-chip font-medium text-primary hover:text-link hover:underline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-link";

export const UNASSIGNED_CONTRACTS_CATALOGUE: TableCatalogue<UnassignedContract> = {
  flexColumnKey: "title",
  defaultColumnKeys: ["reference", "title", "autoDoc", "generator", "createdAt"],
  columns: [
    {
      key: "reference",
      header: <FormattedMessage id="inbox.column.reference" defaultMessage="Ref" />,
      label: (intl) => intl.formatMessage({ id: "inbox.column.reference", defaultMessage: "Ref" }),
      defaultWidth: 88,
      minWidth: 72,
      render: (row, intl) => (
        <span className="font-semibold text-muted">{contractReference(intl, row.number)}</span>
      ),
    },
    {
      key: "title",
      required: true,
      header: <FormattedMessage id="inbox.unassignedContract" defaultMessage="Contract" />,
      label: (intl) =>
        intl.formatMessage({ id: "inbox.unassignedContract", defaultMessage: "Contract" }),
      defaultWidth: 300,
      minWidth: 192,
      render: (row) => (
        <Link className={linkClass} to={`/contracts/${row.number}`}>
          {row.title}
        </Link>
      ),
    },
    {
      key: "autoDoc",
      header: <FormattedMessage id="inbox.unassignedAutoDoc" defaultMessage="Auto-Doc" />,
      label: (intl) =>
        intl.formatMessage({ id: "inbox.unassignedAutoDoc", defaultMessage: "Auto-Doc" }),
      defaultWidth: 208,
      minWidth: 128,
      render: (row) => (
        <Link className={linkClass} to={`/auto-docs/${encodeURIComponent(row.autoDoc.id)}`}>
          {row.autoDoc.name}
        </Link>
      ),
    },
    {
      key: "generator",
      header: <FormattedMessage id="inbox.unassignedGenerator" defaultMessage="Generated by" />,
      label: (intl) =>
        intl.formatMessage({ id: "inbox.unassignedGenerator", defaultMessage: "Generated by" }),
      defaultWidth: 176,
      minWidth: 112,
      render: (row) => row.generator.displayName,
    },
    {
      key: "createdAt",
      header: <FormattedMessage id="inbox.unassignedCreated" defaultMessage="Created" />,
      label: (intl) =>
        intl.formatMessage({ id: "inbox.unassignedCreated", defaultMessage: "Created" }),
      defaultWidth: 144,
      minWidth: 104,
      render: (row, intl) => (
        <span className="text-muted">
          {formatRelativeOrShort(row.createdAt, { locale: intl.locale })}
        </span>
      ),
    },
  ],
};
